services:
  postgres_auth:
    image: postgres:17-alpine
    container_name: postgres_auth
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - app_simple_ecommerce_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_orders:
    image: postgres:17-alpine
    container_name: postgres_orders
    environment:
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: orders_password
      POSTGRES_DB: orders_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_orders_data:/var/lib/postgresql/data
    networks:
      - app_simple_ecommerce_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orders_user -d orders_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_products:
    image: postgres:17-alpine
    container_name: postgres_products
    environment:
      POSTGRES_USER: products_user
      POSTGRES_PASSWORD: products_password
      POSTGRES_DB: products_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_products_data:/var/lib/postgresql/data
    networks:
      - app_simple_ecommerce_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U products_user -d products_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_role:
    image: postgres:17-alpine
    container_name: postgres_role
    environment:
      POSTGRES_USER: role_user
      POSTGRES_PASSWORD: role_password
      POSTGRES_DB: role_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_role_data:/var/lib/postgresql/data
    networks:
      - app_simple_ecommerce_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U role_user -d role_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_users:
    image: postgres:17-alpine
    container_name: postgres_users
    environment:
      POSTGRES_USER: users_user
      POSTGRES_PASSWORD: users_password
      POSTGRES_DB: users_db
    ports:
      - "5436:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    networks:
      - app_simple_ecommerce_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users_user -d users_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  apigateway:
    build:
      context: ./apigateway
      dockerfile: Dockerfile
    env_file: ./docker.env
    volumes:
      - ./docker.env:/app/docker.env
      - ./logs:/var/log/app
      - ./uploads:/app/uploads
    ports:
      - "5000:5000"
    networks:
      - app_simple_ecommerce_network
    depends_on:
      postgres_auth:
        condition: service_healthy
      postgres_orders:
        condition: service_healthy
      postgres_products:
        condition: service_healthy
      postgres_role:
        condition: service_healthy
      postgres_users:
        condition: service_healthy
      kafka:
        condition: service_healthy
      auth:
        condition: service_started
      role:
        condition: service_started
      user:
        condition: service_started
      order:
        condition: service_started
      product:
        condition: service_started
    environment:
      - OTEL_ENDPOINT=otel-collector:4317
      - APP_ENV=docker
      - KAFKA_BROKERS=kafka:9092

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    env_file: ./docker.env
    volumes:
      - ./docker.env:/app/docker.env
      - ./logs:/var/log/app
    networks:
      - app_simple_ecommerce_network
    depends_on:
      postgres_auth:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - OTEL_ENDPOINT=otel-collector:4317
      - APP_ENV=docker
      - KAFKA_BROKERS=kafka:9092
      - DB_HOST=postgres_auth
      - DB_PORT=5432
      - DB_USERNAME=auth_user
      - DB_PASSWORD=auth_password
      - DB_NAME=auth_db

  role:
    build:
      context: ./role
      dockerfile: Dockerfile
    env_file: ./docker.env
    volumes:
      - ./docker.env:/app/docker.env
      - ./logs:/var/log/app
    networks:
      - app_simple_ecommerce_network
    depends_on:
      postgres_role:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - OTEL_ENDPOINT=otel-collector:4317
      - APP_ENV=docker
      - KAFKA_BROKERS=kafka:9092
      - DB_HOST=postgres_role
      - DB_PORT=5432
      - DB_USERNAME=role_user
      - DB_PASSWORD=role_password
      - DB_NAME=role_db

  user:
    build:
      context: ./users
      dockerfile: Dockerfile
    env_file: ./docker.env
    volumes:
      - ./docker.env:/app/docker.env
      - ./logs:/var/log/app
    ports:
      - "50053"
    networks:
      - app_simple_ecommerce_network
    depends_on:
      postgres_users:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - OTEL_ENDPOINT=otel-collector:4317
      - APP_ENV=docker
      - KAFKA_BROKERS=kafka:9092
      - DB_HOST=postgres_users
      - DB_PORT=5432
      - DB_USERNAME=users_user
      - DB_PASSWORD=users_password
      - DB_NAME=users_db

  email:
    build:
      context: ./email
      dockerfile: Dockerfile
    env_file: ./docker.env
    volumes:
      - ./docker.env:/app/docker.env
      - ./logs:/var/log/app
    networks:
      - app_simple_ecommerce_network
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - OTEL_ENDPOINT=otel-collector:4317
      - APP_ENV=docker
      - KAFKA_BROKERS=kafka:9092

  order:
    build:
      context: ./orders
      dockerfile: Dockerfile
    env_file: ./docker.env
    volumes:
      - ./docker.env:/app/docker.env
      - ./logs:/var/log/app
    networks:
      - app_simple_ecommerce_network
    depends_on:
      postgres_orders:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - OTEL_ENDPOINT=otel-collector:4317
      - APP_ENV=docker
      - KAFKA_BROKERS=kafka:9092
      - DB_HOST=postgres_orders
      - DB_PORT=5432
      - DB_USERNAME=orders_user
      - DB_PASSWORD=orders_password
      - DB_NAME=orders_db

  product:
    build:
      context: ./products
      dockerfile: Dockerfile
    env_file: ./docker.env
    volumes:
      - ./docker.env:/app/docker.env
      - ./logs:/var/log/app
    networks:
      - app_simple_ecommerce_network
    depends_on:
      postgres_products:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - OTEL_ENDPOINT=otel-collector:4317
      - APP_ENV=docker
      - KAFKA_BROKERS=kafka:9092
      - DB_HOST=postgres_products
      - DB_PORT=5432
      - DB_USERNAME=products_user
      - DB_PASSWORD=products_password
      - DB_NAME=products_db

  zookeeper:
    image: zookeeper:latest
    container_name: my-zookeeper-ecommerce
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app_simple_ecommerce_network
    healthcheck:
      test: ["CMD-SHELL", "echo stat | nc localhost 2181 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_CLUSTER_ID: kraft-cluster-01
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - app_simple_ecommerce_network
    healthcheck:
      test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s


  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.9.0
    container_name: kafka-exporter
    ports:
      - "9308:9308"
    networks:
      - app_simple_ecommerce_network
    depends_on:
      kafka:
        condition: service_healthy
    command:
      - "--kafka.server=kafka:9092"
      - "--web.listen-address=0.0.0.0:9308"
      - "--log.level=debug"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:9308/metrics || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  postgres_auth_data:
  postgres_orders_data:
  postgres_products_data:
  postgres_role_data:
  postgres_users_data:
  kafka_ecommerce_data:

networks:
  app_simple_ecommerce_network:
    driver: bridge